"""Generic one-shot reroll for a pack-selected creation profile attribute.

Some systems let a player replace one generated characteristic after the
profile's initial rolls. This primitive reuses the exact base/profile dice
expression that generated that characteristic and always replaces the stored
value with the second result. Whether and when the reroll is offered belongs to
``core.creation_flow``; this module only performs the deterministic mutation.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from core.creation_profiles import resolve_creation_profile
from core.dice_engine import DiceRoller
from core.sheets import set_sheet_value, sheet_value


class CreationProfileRerollError(ValueError):
    """A profile reroll target or its pack data is invalid."""


@dataclass(frozen=True)
class CreationProfileRerollResult:
    target: str
    previous: int
    result: int
    expression: str


def _attribute_rules(pack: Any) -> Mapping[str, Any]:
    constraints = getattr(pack, "creation_constraints", {}) or {}
    rules = constraints.get("attributes") or {}
    if not isinstance(rules, Mapping):
        raise CreationProfileRerollError("creation_constraints.attributes must be a mapping")
    return rules


def _profile(pack: Any, profile: str) -> tuple[str, Mapping[str, Any]]:
    resolved = resolve_creation_profile(pack, profile)
    if resolved is None:
        raise CreationProfileRerollError(f"unknown creation profile: {profile}")
    return resolved


def rerollable_profile_attributes(pack: Any, profile: str) -> tuple[str, ...]:
    """Return canonical characteristics generated by the selected profile."""

    _profile_id, raw = _profile(pack, profile)
    overrides = raw.get("attribute_rolls") or {}
    if not isinstance(overrides, Mapping):
        raise CreationProfileRerollError("creation profile attribute_rolls must be a mapping")
    rules = _attribute_rules(pack)
    return tuple(str(key) for key in rules if _roll_expression(rules, overrides, str(key)) is not None)


def _roll_expression(
    rules: Mapping[str, Any],
    overrides: Mapping[str, Any],
    canonical: str,
) -> str | None:
    rule = rules.get(canonical)
    base = rule.get("roll") if isinstance(rule, Mapping) else None
    expression = overrides.get(canonical, base)
    if expression is None:
        return None
    if not isinstance(expression, str) or not expression.strip():
        raise CreationProfileRerollError(
            f"creation reroll expression for {canonical!r} must be a non-empty dice expression"
        )
    return expression.strip()


def reroll_profile_attribute(
    pack: Any,
    character: Any,
    profile: str,
    target: str,
    *,
    roller: DiceRoller | None = None,
) -> CreationProfileRerollResult:
    """Reroll one profile-generated characteristic and keep the new result."""

    _profile_id, raw = _profile(pack, profile)
    rules = _attribute_rules(pack)
    canonical = pack.resolve_skill(target) or str(target).strip()
    if canonical not in rules:
        raise CreationProfileRerollError(f"attribute {target!r} is not rerollable during profile creation")

    overrides = raw.get("attribute_rolls") or {}
    if not isinstance(overrides, Mapping):
        raise CreationProfileRerollError("creation profile attribute_rolls must be a mapping")
    expression = _roll_expression(rules, overrides, canonical)
    if expression is None:
        raise CreationProfileRerollError(f"attribute {canonical!r} has no creation roll expression")

    previous = sheet_value(character, pack, canonical)
    result = (roller or DiceRoller()).roll_expression(expression).total
    set_sheet_value(character, pack, canonical, result)
    return CreationProfileRerollResult(
        target=canonical,
        previous=previous,
        result=result,
        expression=expression,
    )
